import { FormEvent, useState } from 'react';
import { Plus, Save, X } from 'lucide-react';
import { supabase } from '../lib/supabase';
import type { LocationGroup } from '../types/group';

interface Props { isOpen: boolean; groups: readonly LocationGroup[]; onChanged: () => void; onClose: () => void; }

export function GroupManagerModal({ isOpen, groups, onChanged, onClose }: Props) {
  const [label, setLabel] = useState(''); const [color, setColor] = useState('#2563eb'); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  if (!isOpen) return null;
  const create = async (event: FormEvent) => { event.preventDefault(); const name = label.trim(); if (!name) { setError('분야명을 입력하세요.'); return; } if (supabase === null) { setError('Supabase 환경변수 설정을 확인하세요.'); return; }
    setBusy(true); setError(null); const key = `group_${name.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_|_$/g, '') || crypto.randomUUID().replace(/-/g, '')}`.slice(0, 64);
    const { error: requestError } = await supabase.from('location_groups').insert({ key, label: name, color, is_active: true, sort_order: Math.max(0, ...groups.map((group) => group.sortOrder)) + 10 });
    if (requestError) setError(requestError.message); else { setLabel(''); onChanged(); } setBusy(false);
  };
  const save = async (group: LocationGroup, form: HTMLFormElement) => { if (supabase === null || busy) return; const values = new FormData(form); const nextLabel = String(values.get('label') ?? '').trim(); const nextColor = String(values.get('color') ?? ''); const isActive = values.get('isActive') === 'on'; if (!nextLabel) { setError('분야명을 입력하세요.'); return; }
    setBusy(true); setError(null); const { error: requestError } = await supabase.from('location_groups').update({ label: nextLabel, color: nextColor, is_active: isActive }).eq('id', group.id); if (requestError) setError(requestError.message); else onChanged(); setBusy(false); };
  return <div className="fixed inset-0 z-[1200] flex items-center justify-center bg-slate-950/50 p-4" role="dialog" aria-modal="true"><section className="max-h-[88vh] w-full max-w-xl overflow-y-auto rounded-md bg-white shadow-xl"><header className="flex items-center justify-between border-b border-slate-200 px-5 py-4"><div><p className="text-xs font-semibold text-blue-700">관리자</p><h2 className="text-lg font-semibold">분야 관리</h2></div><button className="p-2" onClick={onClose} aria-label="분야 관리 닫기"><X className="size-5" /></button></header><div className="space-y-4 p-5">{error ? <p className="rounded-md bg-red-50 px-3 py-2 text-sm text-red-700">{error}</p> : null}<form onSubmit={(event) => void create(event)} className="grid gap-3 rounded-md border border-slate-200 bg-slate-50 p-3 md:grid-cols-[1fr_auto_auto]"><input className="h-9 rounded-md border border-slate-300 px-2 text-sm" placeholder="새 분야명" value={label} onChange={(event) => setLabel(event.target.value)} disabled={busy}/><input className="h-9 w-full" type="color" value={color} onChange={(event) => setColor(event.target.value)} disabled={busy}/><button className="inline-flex h-9 items-center justify-center gap-1 rounded-md bg-slate-900 px-3 text-sm font-semibold text-white disabled:bg-slate-400" disabled={busy}><Plus className="size-4" />추가</button></form><div className="space-y-3">{groups.map((group) => <form key={group.id} className="grid gap-2 rounded-md border border-slate-200 p-3 md:grid-cols-[1fr_auto_auto_auto]" onSubmit={(event) => { event.preventDefault(); void save(group, event.currentTarget); }}><input name="label" defaultValue={group.label} className="h-9 rounded-md border border-slate-300 px-2 text-sm" disabled={busy}/><input name="color" type="color" defaultValue={group.color} className="h-9 w-full" disabled={busy}/><label className="flex items-center gap-2 text-xs"><input name="isActive" type="checkbox" defaultChecked={group.isActive} disabled={busy}/>활성</label><button className="inline-flex h-9 items-center justify-center rounded-md border border-slate-300 px-3 text-slate-700" disabled={busy} aria-label={`${group.label} 저장`}><Save className="size-4" /></button></form>)}</div></div></section></div>;
}
